@startuml
participant "TxP Server" as TxP
participant "Veridium SDK" as VeridiumSDK
participant "Veridium\nServer" as VeridiumServer

TxP -> VeridiumServer : AuthRequest for SDK
VeridiumServer -> TxP : AuthResponse for SDK
TxP -> VeridiumSDK : Authentication Request
VeridiumSDK -> VeridiumServer : Start authentication (profile)
VeridiumServer -> VeridiumSDK : biometries to check
VeridiumSDK -> VeridiumSDK
note over VeridiumSDK: Perform biometric\nauthentication
VeridiumSDK -> VeridiumServer : Authentication Response
VeridiumSDK -> TxP : Authentication response & identity token
@enduml