@startuml
participant "TxP Server" as TxP
participant "IEEE 2410\nMobile Client" as SDK
participant "IEEE 2410\nServer" as Server

TxP -> Server : AuthRequest for SDK
Server -> TxP : AuthResponse for SDK
TxP -> SDK : Authentication Request
SDK -> Server : Start authentication (profile)
Server -> SDK : biometries to check
SDK -> SDK
note over SDK: Perform biometric\nauthentication
SDK -> Server : Authentication Response
SDK -> TxP : Authentication response & identity token
@enduml