@startuml
autonumber
participant "Mobile App" as MobileApp
participant "Mobile App\nServer" as MobileSrv
participant "IEEE 2410\nMobile SDK" as SDK
participant "IEEE 2410\nServer" as Server

MobileSrv -> Server : **AuthenticationRequest**
note right : VTR
Server -> MobileSrv : **AuthenticationRequest** returns sessionId (& required biometries?)
MobileSrv  --> MobileApp : sessionId for Auth
MobileApp --> SDK : Vendor Authentication Initiated
SDK -> Server : **RegisterSession**
Server -> SDK : **RegisterSession** returns biometries to check (?)
SDK -> SDK : Perform biometric\nauthentication
SDK -> Server : **AuthenticationResponse**
Server -> SDK : **AuthenticationResponse** returns issued identity token
note right : VOT
SDK --> MobileSrv : Authentication response & identity token
@enduml
