@startuml
autonumber
participant "User" as User
participant "Mobile App" as MobileApp
participant "ATM\nTerminal" as ATM
participant "Mobile App\nServer" as MobileSrv

User -> MobileApp : User invokes app
MobileApp -> MobileApp : CWD Initiation\nand Amount Entry
MobileApp -> MobileSrv : Stage user's transaction
User -> ATM : User initiates transaction
ATM --> MobileApp : Pass terminal and session ID
MobileApp -> MobileSrv : Fulfill staged transaction
@enduml
