@startuml
autonumber
participant "User" as User
participant "Mobile App" as MobileApp 
participant "ATM\nTerminal" as ATM
participant "Mobile App\nServer" as MobileSrv
participant "Acquiring\nSwitch" as Switch
participant "Issuing\nAuthorization\nSystem" as Issuer


MobileSrv -> ATM : Staged transaction and bio details
ATM -> ATM : Terminal processing\n+ PIN Block + Bio
ATM -> Switch : Payment Request ISO 8583
Switch -> Issuer : Authorization\nRequest
Issuer --> Switch : Response
Switch --> ATM : Response
ATM -> ATM : Dispense\nCash
MobileSrv -> ATM : Fulfillment\nResponse
MobileSrv -> MobileApp : Acknowledgement
User <->  MobileApp : Ack\nResponse
MobileApp --> MobileSrv : Sync-Up
@enduml
