@startuml
autonumber
participant "User" as User
participant "Vendor\nMobile App" as MobileApp
participant "ATM\nTerminal\nPlugin" as ATM
participant "TxP Server" as TxP
participant "HCE" as HCE
participant "Acquiring\nSwitch" as Switch
participant "Issuing\nAuthorization\nSystem" as Issuer

TxP -> HCE : EMV L2\nCommands
HCE --> TxP : ARQC or AAC
TxP -> ATM : ARQC or AAC
ATM -> ATM : Terminal processing\n+ PIN Block + Bio
ATM -> Switch : Payment Request ISO 8583
Switch -> Issuer : Authorization\nRequest
Issuer --> Switch : ARPC
Switch --> ATM : ARPC
ATM -> ATM : Dispense\nCash
ATM -> TxP : Fulfillment\nResponse
TxP -> MobileApp : Acknowledgement
User ->  MobileApp : Ack\nResponse
MobileApp -> TxP : Sync-Up
@enduml